name: Tests 12 sprint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  test_config:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get testing lib
      run: set -eu && git clone --depth 1 https://github.com/practicum-com/tests-12-public.git
    - name: Installing Dependencies
      run: npm i
    - name: Run test config
      run: cd tests-12-public && bash ./bin/test-config.sh

  test_endpoints:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: '4.4'
    - name: Get testing lib
      run: set -eu && git clone --depth 1 https://github.com/practicum-com/tests-12-public.git
    - name: Run prepare-test-endpoints
      run: cd tests-12-public && bash ./bin/prepare-test-endpoints.sh
    - name: Installing Dependencies
      run: npm i
    - name: Installing wait-port
      run: npm install -g wait-port
    - name: Run server
      run: npm run start & wait-port -t 30000 localhost:3001
    - name: Run test endpoints
      run: cd tests-12-public && bash ./bin/test-endpoints.sh